installCRDs: true
replicaCount: 1
webhook:
    replicaCount: 1
cainjector:
    replicaCount: 1
prometheus:
    enabled: false
global:
    leaderElection:
      namespace: cert-manager
  
extraArgs:
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53