replicaCount: 1
agent:
  enabled: false
service:
  type: ClusterIP
module:
  # from https://github.com/emissary-ingress/emissary/issues/2276
  # strips away any port from the Host header before route mapping
  lua_scripts: |
    function envoy_on_request(request_handle)
      local authority = request_handle:headers():get(":authority")
      if(string.find(authority, ":") ~= nil)
      then
        local authority_index = string.find(authority, ":")
        local stripped_authority = string.sub(authority, 1, authority_index - 1)
        request_handle:headers():replace(":authority", stripped_authority)
      end
    end
  strip_matching_host_port: true # necessary for gRPC, see https://www.getambassador.io/docs/emissary/latest/howtos/grpc/#mappings-with-hosts
  enable_grpc_http11_bridge: true
  enable_grpc_web: true
  cors:
    origins: "*"
    methods: GET, PUT, DELETE, POST, OPTIONS
    headers: authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
    exposed_headers: custom-header-1,grpc-status,grpc-message