config:
  issuer: http://dex:5556
  storage:
    type: memory
  logger:
    level: debug
  web:
    http: 0.0.0.0:5556
    allowedOrigins: ['*']
  oauth2:
    alwaysShowLoginScreen: false
    skipApprovalScreen: true
  staticClients:
    - id: gateway
      name: Monoskope Gateway
      redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
        - http://localhost:3000/auth/callback
      secret: verysecretclientsecret
  enablePasswordDB: true
  staticPasswords:
    - email: admin@monoskope.dev
      hash: $2y$10$bU8BkVI.KNPjcYU0PVu0nOln7iWacVpLR3Q3POeFEjpKUnlVuLISO # bcrypt hash Cost Factor 10
      userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
      username: admin